services:
  db_anix:
    image: postgres
    container_name: db_anix
    restart: always
    ports:
      - 5544:5432
    env_file:
      - .env.docker
    volumes:
      - pg_anix:/var/lib/postgresql/data

  node_app_anix:
    container_name: node_app_anix
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_anix
    env_file:
      - .env.docker

volumes:
  pg_anix:
